version: "3.6"

services:
  strategy:
    build: .
    ports:
      - "65030:65030"
    environment:
      SERVICES_PRICE_URL: http://host.docker.internal:65020
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:65030/actuator/metrics/process.uptime"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s    

networks:
  default:
    name: projectset
    external: true
