server:
  port: 65030
spring:
  application:
    name: strategy

management.endpoints.web.exposure.include: prometheus,health,info,metric
management.health.probes.enabled: true
management:
  endpoint:
    health.show-details: always
    prometheus.enabled: true

services:
  price:
    url: http://localhost:65020